<a href="https://colab.research.google.com/github/Talha1818/Machine-Learning-Python-Notebooks/blob/master/NewAlgoDesignForDocumentsClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/prediction (2) - Copy.csv")

In [3]:
df

   label  probability  actual
0      1         0.97       1
1      1         0.97       1
2      1         0.95       1
3      1         0.98       1
4      1         0.98       1
5      2         0.75       1
6      1         0.99       1
7      1         0.99       1
8      2         0.99       1

In [ ]:
# df.loc[31,'label'] = 1000
# df.loc[31,'probability'] = 0.7

# df.loc[2,'label'] = 2
# df.loc[84,'probability'] = 0.7

# # df.iloc[31]['probability'] = 0.7

In [30]:
# !pip install tabulate
from tabulate import tabulate

In [ ]:
from tabulate import tabulate
print(tabulate(df, headers = 'keys', tablefmt = 'psql'))

+----+---------+---------------+----------+
|    |   label |   probability |   actual |
|----+---------+---------------+----------|
|  0 |       1 |          0.97 |        1 |
|  1 |       1 |          0.97 |        1 |
|  2 |       1 |          0.95 |        1 |
|  3 |       1 |          0.98 |        1 |
|  4 |       1 |          0.98 |        1 |
|  5 |       2 |          0.75 |        1 |
|  6 |       1 |          0.99 |        1 |
|  7 |       1 |          0.99 |        1 |
|  8 |       2 |          0.99 |        1 |
+----+---------+---------------+----------+

In [ ]:
df1 = df['label'].value_counts().to_frame().reset_index().rename(columns={'index':'label','label':'count'})
one_category = df1[df1['count']==1]
one_category_list= one_category['label'].tolist()
print(one_category_list)

[]

In [ ]:
s = df[['label', 'probability']].values.tolist()

THRESHOLD = 0.8
for i in range(len(s)-1):
    if s[i][0] in one_category_list:
        pass
#         print(f"\nCategory 1 {s[i][0]} Prob {s[i][1]}\n")
    elif s[i][0]==s[i+1][0]:
        pass
#         print(f"Previous {s[i][0]}| Next {s[i+1][0]}")
    else:
        if (s[i][1]<THRESHOLD or s[i+1][1]<THRESHOLD) and not (s[i][0] in one_category_list or s[i+1][0] in one_category_list):
            prev_ = s[i][0]
            prev1 = s[i-1][0]
            next_ = s[i+1][0]
            next1 = s[i+2][0]
            next2 = s[i+3][0]
            print(f"Index:{i}  Previous1 {prev1} | Previous {prev_} Prob {s[i][1]} \t| Next {next_} Prob {s[i+1][1]} | Next1 {next1} | Next2 {next2}")
            if (prev_==next1 and prev_==next2) and (prev_==prev1):
                print("="*100)
                print(f"\t\tWe need to set {prev1} at INDEX {i+1}")
                print("="*100)              
                df.loc[i+1,'label'] = prev1
#                 df.loc[i,'probability'] = 0.7

Index:4  Previous1 1.0 | Previous 1.0 Prob 0.98 	| Next 2.0 Prob 0.75 | Next1 1.0 | Next2 1.0
====================================================================================================
		We need to set 1.0 at INDEX 5
====================================================================================================
Index:5  Previous1 1.0 | Previous 2.0 Prob 0.75 	| Next 1.0 Prob 0.99 | Next1 1.0 | Next2 2.0

In [ ]:
print(tabulate(df, headers = 'keys', tablefmt = 'psql'))

+----+---------+---------------+----------+
|    |   label |   probability |   actual |
|----+---------+---------------+----------|
|  0 |       1 |          0.97 |        1 |
|  1 |       1 |          0.97 |        1 |
|  2 |       1 |          0.95 |        1 |
|  3 |       1 |          0.98 |        1 |
|  4 |       1 |          0.98 |        1 |
|  5 |       1 |          0.75 |        1 |
|  6 |       1 |          0.99 |        1 |
|  7 |       1 |          0.99 |        1 |
|  8 |       2 |          0.99 |        1 |
+----+---------+---------------+----------+

**New Alog**

In [5]:
df

   label  probability  actual
0      1         0.97       1
1      1         0.97       1
2      1         0.95       1
3      1         0.98       1
4      1         0.98       1
5      2         0.75       1
6      1         0.99       1
7      1         0.99       1
8      2         0.99       1

In [9]:
df.loc[5, 'label'] = 27

In [10]:
df

   label  probability  actual
0      1         0.97       1
1      1         0.97       1
2      1         0.95       1
3      1         0.98       1
4      1         0.98       1
5     27         0.75       1
6      1         0.99       1
7      1         0.99       1
8      2         0.99       1

In [41]:
df = pd.read_csv('/content/test (1).csv')
from tabulate import tabulate
print(tabulate(df, headers = 'keys', tablefmt = 'psql'))

+----+----------+---------------+---------+
|    |   actual |   probability |   label |
|----+----------+---------------+---------|
|  0 |        1 |        0.9975 |       1 |
|  1 |        1 |        0.9983 |       1 |
|  2 |        1 |        0.9982 |       1 |
|  3 |        1 |        0.9983 |       1 |
|  4 |        1 |        0.9981 |       1 |
|  5 |        2 |        0.9569 |       1 |
|  6 |       11 |        0.999  |      11 |
|  7 |       11 |        0.999  |      11 |
|  8 |       13 |        0.9981 |      13 |
|  9 |       13 |        0.9917 |      13 |
| 10 |       14 |        0.998  |      14 |
| 11 |       14 |        0.9979 |      14 |
| 12 |       14 |        0.9981 |      14 |
| 13 |       14 |        0.9982 |      14 |
| 14 |       14 |        0.9981 |      14 |
| 15 |       14 |        0.9982 |      14 |
| 16 |       12 |        0.9979 |      12 |
| 17 |       12 |        0.9981 |      12 |
| 18 |       12 |        0.9984 |      12 |
| 19 |        3 |        0.9994 |       3 |
| 20 |        3 |        0.9994 |       3 |
| 21 |        2 |        0.9973 |       2 |
| 22 |        2 |        0.9974 |       2 |
| 23 |        2 |        0.9945 |       2 |
| 24 |        2 |        0.9029 |       2 |
| 25 |        2 |        0.8319 |       2 |
| 26 |       29 |        0.9996 |      29 |
| 27 |       30 |        0.9987 |      30 |
| 28 |       30 |        0.9982 |      30 |
| 29 |       30 |        0.9983 |      30 |
| 30 |       30 |        0.9982 |      30 |
| 31 |       30 |        0.9983 |      30 |
| 32 |       30 |        0.9981 |      30 |
| 33 |       30 |        0.9984 |      30 |
| 34 |       30 |        0.9988 |      30 |
| 35 |       36 |        0.9991 |      36 |
| 36 |       27 |        0.9997 |      27 |
| 37 |       20 |        0.9988 |      20 |
| 38 |       20 |        0.9975 |      20 |
| 39 |       20 |        0.9979 |      20 |
| 40 |       20 |        0.9966 |      20 |
| 41 |       20 |        0.9986 |      20 |
| 42 |       20 |        0.9985 |      20 |
| 43 |       20 |        0.9981 |      20 |
| 44 |       20 |        0.9988 |      20 |
| 45 |       20 |        0.9988 |      20 |
| 46 |       20 |        0.9982 |      20 |
| 47 |       15 |        0.9991 |      15 |
| 48 |       15 |        0.9986 |      15 |
| 49 |       15 |        0.9983 |      15 |
| 50 |       15 |        0.9981 |      15 |
| 51 |       15 |        0.9987 |      15 |
| 52 |       15 |        0.9991 |      15 |
| 53 |       15 |        0.9977 |      15 |
| 54 |       15 |        0.9986 |      15 |
| 55 |       15 |        0.9984 |      15 |
| 56 |       24 |        0.9998 |      24 |
| 57 |       24 |        0.9998 |      24 |
| 58 |       25 |        0.9989 |      25 |
| 59 |       28 |        0.9831 |      28 |
| 60 |       21 |        0.9981 |      21 |
| 61 |       21 |        0.9986 |      21 |
| 62 |       39 |        0.9991 |      39 |
| 63 |       35 |        0.9986 |      35 |
| 64 |       35 |        0.9984 |      35 |
| 65 |       37 |        0.9988 |      37 |
| 66 |       37 |        0.997  |      37 |
| 67 |      111 |        0.9987 |      38 |
| 68 |       45 |        0.9996 |      45 |
| 69 |       42 |        0.9965 |      42 |
| 70 |       42 |        0.9965 |      42 |
| 71 |       42 |        0.9965 |      42 |
| 72 |       41 |        0.995  |      41 |
| 73 |       41 |        0.995  |      41 |
| 74 |       41 |        0.9949 |      41 |
| 75 |       43 |        0.993  |      43 |
| 76 |       43 |        0.9855 |      43 |
| 77 |       43 |        0.9929 |      43 |
| 78 |       22 |        0.9994 |      22 |
| 79 |       44 |        0.9989 |      44 |
| 80 |       40 |        0.9997 |      40 |
| 81 |       40 |        0.9997 |      40 |
| 82 |       40 |        0.9997 |      40 |
| 83 |       40 |        0.9997 |      40 |
| 84 |       40 |        0.9997 |      40 |
| 85 |       40 |        0.9997 |      40 |
| 86 |       40 |        0.9997 |      40 |
| 87 |       23 |        0.9996 |      23 |
| 88 |       23 |        0.9994 |      23 |
| 89 |       36 |        0.999  |     614 |
+----+----------+---------------+---------+

In [52]:
df.loc[30, 'label'] = 34
df.loc[30, 'probability'] = 0.90

In [53]:
#copying the dataframe to perform experiment
test_df = df.copy()


threshold = 0.97 #Setting the threshold value. Above than 96% seems to be good score

#List of documents that appear as a single page document in the package
single_list= [27, 29, 36, 38, 39, 44, 45, 614, 63, 71, 74, 
             76, 79, 80, 82, 84, 100, 103, 109, 110, 113, 117, 
             138, 197, 203, 75, 170, 102, 130, 160, 168, 183, 224, 228, 257]

#Initializing the variables
accurate = 0
total = 0


#getting the current accuracy of the package.

for i in range(test_df['label'].count()):
  if (test_df['label'][i] == test_df['actual'][i]):
    accurate +=1
  total +=1

print("score is: "+ str(round(accurate/total, 2)*100)+ "%")

score is: 96.0%

In [54]:
#Performing the actual algorithm. 


'''
We have restricted ourselves with a fact that 
eliminating false positives is a hard job to do.
Therefore, we are handling cases in which multipaged documents appears to be 
wrong document. This algorithm flaws only at one point i.e.
when we have single page document perdicted with higher accuracy above than threshold
and assigned label is also a single paged document but both are different.

Surprisingly, we are getting 1-2% accuracy improvements with postprocessing.

"actual" means what we actually got after passing from prediction
"probability" means confidence score assigned
"label" means label assigned to the document page
'''


for i in range(1, test_df['label'].count()-1):
  
  if (test_df['probability'][i] < threshold):
    if (int(test_df['label'][i]) not in single_list):
      if ((test_df['label'][i] != test_df['label'][i+1]) and (test_df['label'][i] != test_df['label'][i-1])):
        test_df['label'][i] = test_df['label'][i-1] 

        test_df['probability'][i] = 2.00 # This is redundant, unncessary. please ignore it while writing in the code
        


accurate = 0
total = 0

#Doing the same thing again

for i in range(test_df['label'].count()):
  if (test_df['label'][i] == test_df['actual'][i]):
    accurate +=1
  else:
      print(i, test_df['label'][i], test_df['actual'][i], test_df['probability'][i])
  total +=1

print("score is: "+ str(round(accurate/total, 2)*100)+ "%")

print(total-accurate)

5 1 2 0.9569
67 38 111 0.9987
89 614 36 0.999
score is: 97.0%
3

<ipython-input-54-5d3283e28da1>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['label'][i] = test_df['label'][i-1]
<ipython-input-54-5d3283e28da1>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['probability'][i] = 2.00 # This is redundant, unncessary. please ignore it while writing in the code

In [55]:
print(tabulate(test_df, headers = 'keys', tablefmt = 'psql'))

+----+----------+---------------+---------+
|    |   actual |   probability |   label |
|----+----------+---------------+---------|
|  0 |        1 |        0.9975 |       1 |
|  1 |        1 |        0.9983 |       1 |
|  2 |        1 |        0.9982 |       1 |
|  3 |        1 |        0.9983 |       1 |
|  4 |        1 |        0.9981 |       1 |
|  5 |        2 |        0.9569 |       1 |
|  6 |       11 |        0.999  |      11 |
|  7 |       11 |        0.999  |      11 |
|  8 |       13 |        0.9981 |      13 |
|  9 |       13 |        0.9917 |      13 |
| 10 |       14 |        0.998  |      14 |
| 11 |       14 |        0.9979 |      14 |
| 12 |       14 |        0.9981 |      14 |
| 13 |       14 |        0.9982 |      14 |
| 14 |       14 |        0.9981 |      14 |
| 15 |       14 |        0.9982 |      14 |
| 16 |       12 |        0.9979 |      12 |
| 17 |       12 |        0.9981 |      12 |
| 18 |       12 |        0.9984 |      12 |
| 19 |        3 |        0.9994 |       3 |
| 20 |        3 |        0.9994 |       3 |
| 21 |        2 |        0.9973 |       2 |
| 22 |        2 |        0.9974 |       2 |
| 23 |        2 |        0.9945 |       2 |
| 24 |        2 |        0.9029 |       2 |
| 25 |        2 |        0.8319 |       2 |
| 26 |       29 |        0.9996 |      29 |
| 27 |       30 |        0.9987 |      30 |
| 28 |       30 |        0.9982 |      30 |
| 29 |       30 |        0.9983 |      30 |
| 30 |       30 |        2      |      30 |
| 31 |       30 |        0.9983 |      30 |
| 32 |       30 |        0.9981 |      30 |
| 33 |       30 |        0.9984 |      30 |
| 34 |       30 |        0.9988 |      30 |
| 35 |       36 |        0.9991 |      36 |
| 36 |       27 |        0.9997 |      27 |
| 37 |       20 |        0.9988 |      20 |
| 38 |       20 |        0.9975 |      20 |
| 39 |       20 |        0.9979 |      20 |
| 40 |       20 |        0.9966 |      20 |
| 41 |       20 |        0.9986 |      20 |
| 42 |       20 |        0.9985 |      20 |
| 43 |       20 |        0.9981 |      20 |
| 44 |       20 |        0.9988 |      20 |
| 45 |       20 |        0.9988 |      20 |
| 46 |       20 |        0.9982 |      20 |
| 47 |       15 |        0.9991 |      15 |
| 48 |       15 |        0.9986 |      15 |
| 49 |       15 |        0.9983 |      15 |
| 50 |       15 |        0.9981 |      15 |
| 51 |       15 |        0.9987 |      15 |
| 52 |       15 |        0.9991 |      15 |
| 53 |       15 |        0.9977 |      15 |
| 54 |       15 |        0.9986 |      15 |
| 55 |       15 |        0.9984 |      15 |
| 56 |       24 |        0.9998 |      24 |
| 57 |       24 |        0.9998 |      24 |
| 58 |       25 |        0.9989 |      25 |
| 59 |       28 |        0.9831 |      28 |
| 60 |       21 |        0.9981 |      21 |
| 61 |       21 |        0.9986 |      21 |
| 62 |       39 |        0.9991 |      39 |
| 63 |       35 |        0.9986 |      35 |
| 64 |       35 |        0.9984 |      35 |
| 65 |       37 |        0.9988 |      37 |
| 66 |       37 |        0.997  |      37 |
| 67 |      111 |        0.9987 |      38 |
| 68 |       45 |        0.9996 |      45 |
| 69 |       42 |        0.9965 |      42 |
| 70 |       42 |        0.9965 |      42 |
| 71 |       42 |        0.9965 |      42 |
| 72 |       41 |        0.995  |      41 |
| 73 |       41 |        0.995  |      41 |
| 74 |       41 |        0.9949 |      41 |
| 75 |       43 |        0.993  |      43 |
| 76 |       43 |        0.9855 |      43 |
| 77 |       43 |        0.9929 |      43 |
| 78 |       22 |        0.9994 |      22 |
| 79 |       44 |        0.9989 |      44 |
| 80 |       40 |        0.9997 |      40 |
| 81 |       40 |        0.9997 |      40 |
| 82 |       40 |        0.9997 |      40 |
| 83 |       40 |        0.9997 |      40 |
| 84 |       40 |        0.9997 |      40 |
| 85 |       40 |        0.9997 |      40 |
| 86 |       40 |        0.9997 |      40 |
| 87 |       23 |        0.9996 |      23 |
| 88 |       23 |        0.9994 |      23 |
| 89 |       36 |        0.999  |     614 |
+----+----------+---------------+---------+